#### A LOT OF INPUT !!!!!!

z <- data.frame(CSHPI$numpanels1x_noreligion, 
                CSHPI$numpanels1x_jd_public, 
                CSHPI$numpanels1x_dem, 
                CSHPI$numpanels2x_dem, 
                CSHPI$numpanels3x_dem, 
                (CSHPI$numpanels1x_dem)^2, 
                (CSHPI$numpanels1x_dem)^3, 
                CSHPI$numpanels1x_female, 
                CSHPI$numpanels2x_female,
                CSHPI$numpanels3x_female, 
                CSHPI$numpanels1x_nonwhite,
                CSHPI$numpanels2x_nonwhite,
                CSHPI$numpanels3x_nonwhite, 
                CSHPI$numpanels1x_black,
                CSHPI$numpanels2x_black,
                CSHPI$numpanels3x_black, 
                CSHPI$numpanels1x_jewish,
                CSHPI$numpanels2x_jewish,
                CSHPI$numpanels3x_jewish, 
                CSHPI$numpanels1x_catholic,
                CSHPI$numpanels2x_catholic,
                CSHPI$numpanels3x_catholic, 
                CSHPI$numpanels2x_noreligion,
                CSHPI$numpanels3x_noreligion, 
                CSHPI$numpanels1x_instate_ba,
                CSHPI$numpanels2x_instate_ba,
                CSHPI$numpanels3x_instate_ba, 
                CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels2x_ba_public,
                CSHPI$numpanels3x_ba_public, 
                CSHPI$numpanels2x_jd_public,
                CSHPI$numpanels3x_jd_public, 
                (CSHPI$numpanels1x_jd_public)^2/5,
                (CSHPI$numpanels1x_jd_public)^3/25, 
                CSHPI$numpanels1x_elev,
                CSHPI$numpanels2x_elev,
                CSHPI$numpanels3x_elev, 
                (CSHPI$numpanels1x_elev)^2,
                (CSHPI$numpanels1x_elev)^3, 
                CSHPI$numpanels1x_female_black,
                CSHPI$numpanels2x_female_black,
                CSHPI$numpanels3x_female_black, 
                CSHPI$numpanels1x_female_noreligion,
                CSHPI$numpanels2x_female_noreligion,
                CSHPI$numpanels3x_female_noreligion, 
                CSHPI$numpanels1x_black_noreligion,
                CSHPI$numpanels2x_black_noreligion,
                CSHPI$numpanels3x_black_noreligion, 
                CSHPI$numpanels1x_female_jd_public,
                CSHPI$numpanels2x_female_jd_public, 
                CSHPI$numpanels3x_female_jd_public, 
                CSHPI$numpanels1x_black_jd_public,
                CSHPI$numpanels2x_black_jd_public, 
                CSHPI$numpanels3x_black_jd_public, 
                CSHPI$numpanels1x_noreligion_jd_pub,
                CSHPI$numpanels2x_noreligion_jd_pub, 
                CSHPI$numpanels3x_noreligion_jd_pub, 
                CSHPI$numpanels1x_mainline,
                CSHPI$numpanels2x_mainline,
                CSHPI$numpanels3x_mainline, 
                CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels2x_evangelical, 
                CSHPI$numpanels3x_evangelical, 
                CSHPI$numpanels1x_protestant,
                CSHPI$numpanels2x_protestant,
                CSHPI$numpanels3x_protestant, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_female,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_black, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_jd_public,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels1x_dem *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels1x_dem * CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_jd_public,
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels1x_female *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels1x_jd_public *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels1x_ba_public *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels2x_jd_public *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_noreligion, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels3x_jd_public *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_jd_public,
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_ba_public,
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels2x_female *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels2x_ba_public *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_instate_ba, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_elev, 
                CSHPI$numpanels1x_instate_ba *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_noreligion, 
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_elev *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_noreligion, 
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_evangelical,
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_protestant, 
                CSHPI$numpanels1x_protestant *  CSHPI$numpanels1x_nonwhite, 
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_jewish,
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_catholic, 
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_noreligion,
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_evangelical, 
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_mainline, 
                CSHPI$numpanels1x_mainline *  CSHPI$numpanels1x_nonwhite )

names(z) <- cbind('1x_noreligion',
                  '1x_jd_public',
                  '1x_dem',
                  '2x_dem',
                  '3x_dem', 
                  '1x_dem^2',
                  '1x_dem^3', 
                  '1x_female',
                  '2x_female',
                  '3x_female', 
                  '1x_nonwhite',
                  '2x_nonwhite',
                  '3x_nonwhite', 
                  '1x_black',
                  '2x_black',
                  '3x_black', 
                  '1x_jewish',
                  '2x_jewish',
                  '3x_jewish', 
                  '1x_catholic',
                  '2x_catholic',
                  '3x_catholic', 
                  '2x_noreligion',
                  '3x_noreligion', 
                  '1x_instate_ba',
                  '2x_instate_ba',
                  '3x_instate_ba', 
                  '1x_ba_public',
                  '2x_ba_public',
                  '3x_ba_public', 
                  '2x_jd_public',
                  '3x_jd_public', 
                  '1x_jd_public^2',
                  '1x_jd_public^3', 
                  '1x_elev',
                  '2x_elev',
                  '3x_elev', 
                  '1x_elev^2',
                  '1x_elev^3', 
                  '1x_female_black',
                  '2x_female_black',
                  '3x_female_black', 
                  '1x_female_noreligion',
                  '2x_female_noreligion',
                  '3x_female_noreligion', 
                  '1x_black_noreligion',
                  '2x_black_noreligion',
                  '3x_black_noreligion', 
                  '1x_female_jd_public',
                  '2x_female_jd_public',
                  '3x_female_jd_public', 
                  '1x_black_jd_public',
                  '2x_black_jd_public',
                  '3x_black_jd_public', 
                  '1x_noreligion_jd_pub',
                  '2x_noreligion_jd_pub',
                  '3x_noreligion_jd_pub', 
                  '1x_mainline',
                  '2x_mainline',
                  '3x_mainline', 
                  '1x_evangelical',
                  '2x_evangelical',
                  '3x_evangelical', 
                  '1x_protestant',
                  '2x_protestant',
                  '3x_protestant', 
                  '1x_dem.*1x_female',
                  '1x_dem.*1x_black', 
                  '1x_dem.*1x_jewish',
                  '1x_dem.*1x_catholic', 
                  '1x_dem.*1x_noreligion',
                  '1x_dem.*1x_ba_public', 
                  '1x_dem.*1x_jd_public',
                  '1x_dem.*1x_mainline', 
                  '1x_dem.*1x_evangelical',
                  '1x_dem.*1x_protestant', 
                  '1x_dem.*1x_ba_public',
                  '1x_dem.*1x_elev',
                  '1x_dem.*1x_nonwhite',
                  '1x_female.*1x_jewish',
                  '1x_female.*1x_catholic', 
                  '1x_female.*1x_noreligion',
                  '1x_female.*1x_ba_public', 
                  '1x_female.*1x_jd_public',
                  '1x_female.*1x_mainline', 
                  '1x_female.*1x_evangelical',
                  '1x_female.*1x_protestant', 
                  '1x_female.*1x_ba_public',
                  '1x_female.*1x_elev',
                  '1x_female.*1x_nonwhite',
                  '1x_jd_public.*1x_jewish',
                  '1x_jd_public.*1x_catholic', 
                  '1x_jd_public.*1x_noreligion',
                  '1x_jd_public.*1x_instate_ba', 
                  '1x_jd_public.*1x_mainline', 
                  '1x_jd_public.*1x_evangelical',
                  '1x_jd_public.*1x_protestant', 
                  '1x_jd_public.*1x_ba_public',
                  '1x_jd_public.*1x_elev', 
                  '1x_jd_public.*1x_nonwhite', 
                  '1x_ba_public.*1x_jewish',
                  '1x_ba_public.*1x_catholic', 
                  '1x_ba_public.*1x_noreligion',
                  '1x_ba_public.*1x_instate_ba', 
                  '1x_ba_public.*1x_mainline', 
                  '1x_ba_public.*1x_evangelical',
                  '1x_ba_public.*1x_protestant', 
                  '1x_ba_public.*1x_elev', 
                  '1x_ba_public.*1x_nonwhite', 
                  '2x_jd_public.*1x_jewish',
                  '2x_jd_public.*1x_catholic', 
                  '2x_jd_public.*1x_noreligion',
                  '2x_jd_public.*1x_instate_ba', 
                  '2x_jd_public.*1x_mainline', 
                  '2x_jd_public.*1x_evangelical',
                  '2x_jd_public.*1x_protestant', 
                  '2x_jd_public.*1x_ba_public',
                  '2x_jd_public.*1x_elev', 
                  '2x_jd_public.*1x_nonwhite', 
                  '3x_jd_public.*1x_jewish',
                  '3x_jd_public.*1x_catholic', 
                  '3x_jd_public.*1x_noreligion',
                  '3x_jd_public.*1x_instate_ba', 
                  '3x_jd_public.*1x_mainline', 
                  '3x_jd_public.*1x_evangelical',
                  '3x_jd_public.*1x_protestant', 
                  '3x_jd_public.*1x_ba_public',
                  '3x_jd_public.*1x_elev', 
                  '3x_jd_public.*1x_nonwhite', 
                  '2x_female.*1x_jewish',
                  '2x_female.*1x_catholic', 
                  '2x_female.*1x_noreligion',
                  '2x_female.*1x_ba_public', 
                  '2x_female.*1x_jd_public',
                  '2x_female.*1x_mainline', 
                  '2x_female.*1x_evangelical',
                  '2x_female.*1x_protestant', 
                  '2x_female.*1x_ba_public',
                  '2x_female.*1x_elev',
                  '2x_female.*1x_nonwhite',
                  '2x_ba_public.*1x_jewish',
                  '2x_ba_public.*1x_catholic', 
                  '2x_ba_public.*1x_noreligion',
                  '2x_ba_public.*1x_instate_ba', 
                  '2x_ba_public.*1x_mainline', 
                  '2x_ba_public.*1x_evangelical',
                  '2x_ba_public.*1x_protestant', 
                  '2x_ba_public.*1x_elev', 
                  '2x_ba_public.*1x_nonwhite', 
                  '1x_instate_ba.*1x_jewish',
                  '1x_instate_ba.*1x_catholic', 
                  '1x_instate_ba.*1x_noreligion',
                  '1x_instate_ba.*1x_instate_ba', 
                  '1x_instate_ba.*1x_mainline', 
                  '1x_instate_ba.*1x_evangelical',
                  '1x_instate_ba.*1x_protestant', 
                  '1x_instate_ba.*1x_elev', 
                  '1x_instate_ba.*1x_nonwhite',
                  '1x_elev.*1x_jewish',
                  '1x_elev.*1x_catholic', 
                  '1x_elev.*1x_noreligion',
                  '1x_elev.*1x_mainline', 
                  '1x_elev.*1x_evangelical',
                  '1x_elev.*1x_protestant', 
                  '1x_elev.*1x_nonwhite', 
                  '1x_protestant.*1x_jewish',
                  '1x_protestant.*1x_catholic', 
                  '1x_protestant.*1x_noreligion',
                  '1x_protestant.*1x_mainline', 
                  '1x_protestant.*1x_evangelical',
                  '1x_protestant.*1x_protestant', 
                  '1x_protestant.*1x_nonwhite', 
                  '1x_mainline.*1x_jewish',
                  '1x_mainline.*1x_catholic', 
                  '1x_mainline.*1x_noreligion', 
                  '1x_mainline.*1x_evangelical',
                  '1x_mainline.*1x_mainline', 
                  '1x_mainline.*1x_nonwhite')
